'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const E=require('../public/js/benyehuda-learning-edition');
const C=require('../public/js/corpus-discovery-core');
const bytes=x=>new TextEncoder().encode(JSON.stringify(x));
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
function fixture(){const bundle={library:{texts:[{text_key:'b'.repeat(64),corpus:{byehuda_id:'28026'},source_meta:{public_learning:{edition_id:'e'.repeat(64)}},rows:[{hebrew_plain:'טקסט'}]}]}};const raw=bytes(bundle);return{bundle,raw,card:{id:'28026',file:'works/28026-'+hash(raw).slice(0,32)+'.json',bundle_sha256:hash(raw),text_key:'b'.repeat(64),learning_edition_id:'e'.repeat(64),segments:1}};}
test('device policy keeps an earlier edition until a separate published edition is opened',()=>{const {card}=fixture();assert.deepEqual(E.deviceChoice(card,null,['previous'],false),{id:'previous',edition:'previous'});assert.deepEqual(E.deviceChoice(card,null,['previous'],true),{id:null,edition:'published'});assert.deepEqual(E.deviceChoice(card,'current',['previous'],false),{id:'current',edition:'published'});});
test('publication checksum binds the work ID, rows, key and edition',async()=>{const {card,raw}=fixture();assert.equal((await E.verifyBundle(card,raw)).library.texts[0].corpus.byehuda_id,'28026');await assert.rejects(E.verifyBundle({...card,id:'3557'},raw),/identity/);await assert.rejects(E.verifyBundle({...card,segments:2},raw),/identity/);const corrupted=raw.slice();corrupted[corrupted.length-2]^=1;await assert.rejects(E.verifyBundle(card,corrupted),/hash/);});
test('publication bundles cannot invoke destructive canon reconcile',async()=>{const {card,bundle}=fixture();bundle.library.canon_version=4;const raw=bytes(bundle);await assert.rejects(E.verifyBundle({...card,bundle_sha256:hash(raw)},raw),/reconcile/);});
test('release identity rejects duplicate works even when the checksum is valid',async()=>{const m={catalog_version:8,works:[{work_id:'1'}],retained_works:[{work_id:'1'}]},raw=bytes(m);await assert.rejects(E.verifyManifest({version:8,release_manifest_sha256:hash(raw),counts:{baked:2},pointers:{ready:['1','1']}},raw),/manifest/);});
test('published layer counts describe the study edition, without claiming local rows or human review',()=>{const card={id:'28026',segments:3,bundle_sha256:'a'.repeat(64),review_status:'machine',coverage:{text:true,translation:'machine',niqqud:1,audio:'none'},public_learning:{schema:'benyehuda-public-learning-v1',work_id:'28026',main_rows:3,complete_learning_edition:true,filled_rows:{russian:3,translit:3,translit_ru:2},niqqud_rows:2}};const facts=C.describeMaterial(card,{localText:true});assert.equal(facts.coverage.translation.status,'full');assert.equal(facts.coverage.translation.scope,'learning-edition');assert.equal(facts.coverage.transliteration.status,'partial');assert.equal(facts.coverage.niqqud.status,'partial');assert.equal(facts.version.currentLocalVersion,'unverified');assert.equal(facts.provenance.assertedReviewStatus,'machine');const invalid=C.describeMaterial({...card,segments:4});assert.equal(invalid.coverage.translation.status,'present');});
