const test = require('node:test');
const assert = require('node:assert/strict');
const Core = require('../public/js/import-center-core.js');

const H = (char) => char.repeat(64);

function material(overrides = {}) {
  return {
    material_id: 'material-1',
    portable_scope_id: 'learning-material:sha256:' + H('a'),
    portable_text_key: 'lesson-1',
    title: 'שיעור Мия',
    projection_present: true,
    projection_archived: false,
    projection_rebuildable: false,
    caption_raw_present: true,
    caption_current_revision_id: 'caption-4',
    caption_current_sha256: H('b'),
    caption_draft_present: false,
    table_current_revision_id: 'table-2',
    table_content_sha256: H('c'),
    table_mapping_sha256: H('d'),
    table_bound_caption_revision_id: 'caption-4',
    table_bound_caption_revision_sha256: H('b'),
    mapping_total: 2,
    mapping_mapped: 2,
    mapping_invalid: false,
    media_expected_sha256: H('e'),
    media_actual_sha256: H('e'),
    media_present: true,
    media_codec_supported: true,
    import_integrity_state: 'complete',
    import_receipt_id: 'import-1',
    source_state_sha256: H('f'),
    ...overrides,
  };
}

function savedReceipt(sourceState = H('f'), format = 'archive_lplp') {
  return {
    receipt_id: 'saved-1', event_kind: 'owner_saved', parent_receipt_id: 'generated-1',
    scope_kind: 'material', portable_scope_id: 'learning-material:sha256:' + H('a'),
    format_kind: format, source_state_sha256: sourceState, artifact_sha256: H('9'),
    destination_kind: 'files_icloud', created_at: '2026-08-02T10:00:00.000Z',
  };
}

test('lifecycle truth never promotes a compatibility projection into material canon', () => {
  const [view] = Core.buildCatalog([material({
    material_id: null,
    projection_present: true,
    projection_rebuildable: false,
    caption_raw_present: false,
    caption_current_revision_id: null,
    table_current_revision_id: null,
    import_integrity_state: 'conflict',
  })], [], {}, '2026-08-02T12:00:00.000Z');
  assert.equal(view.projection_state, 'conflict');
  assert.equal(view.caption_state, 'missing');
  assert.equal(view.table_state, 'missing');
  assert.equal(view.continuity_state, 'blocked');
  assert.equal(view.next_action, 'inspect-recovery');
});

test('generated bytes and an explicit owner-saved assertion remain different backup states', () => {
  const generated = { ...savedReceipt(), receipt_id: 'generated-1', event_kind: 'generated', parent_receipt_id: null, destination_kind: null };
  const [onlyGenerated] = Core.buildCatalog([material()], [generated], {});
  const [confirmed] = Core.buildCatalog([material()], [generated, savedReceipt()], {});
  assert.equal(onlyGenerated.backup_state, 'generated-unconfirmed');
  assert.equal(onlyGenerated.next_action, 'confirm-backup');
  assert.equal(confirmed.backup_state, 'current');
  assert.equal(confirmed.next_action, 'continue-study');
});

test('compatibility JSON never proves a canonical backup and changed state hashes make saved backup stale', () => {
  const [compatibility] = Core.buildCatalog([material()], [savedReceipt(H('f'), 'compatibility_json')], {});
  const generated = { ...savedReceipt(H('8')), receipt_id: 'generated-1', event_kind: 'generated', parent_receipt_id: null, destination_kind: null };
  const [stale] = Core.buildCatalog([material()], [generated, savedReceipt(H('8'))], {});
  assert.equal(compatibility.backup_state, 'none');
  assert.equal(stale.backup_state, 'stale');
  assert.equal(stale.next_action, 'create-backup');
});

test('recovery routing is fail-closed and archived projections unarchive without re-import', () => {
  const states = Core.buildCatalog([
    material({ material_id: 'conflict', import_integrity_state: 'conflict' }),
    material({ material_id: 'archived', projection_archived: true, import_integrity_state: 'archived' }),
    material({ material_id: 'binding', import_integrity_state: 'repairable-binding' }),
    material({ material_id: 'source', projection_present: false, projection_rebuildable: true, import_integrity_state: 'repairable-source' }),
  ], [], {});
  assert.deepEqual(states.map((x) => x.next_action), ['inspect-recovery', 'unarchive', 'repair-binding', 'recover-from-package']);
});

test('storage and media diagnostics preserve study when bytes are absent and separate mismatch from codec support', () => {
  const [missing, mismatch, codec] = Core.buildCatalog([
    material({ material_id: 'missing', media_present: false, media_actual_sha256: null }),
    material({ material_id: 'mismatch', media_actual_sha256: H('7') }),
    material({ material_id: 'codec', media_codec_supported: false }),
  ], [], {});
  assert.equal(missing.media_state, 'missing');
  assert.equal(missing.continuity_state, 'needs-media');
  assert.equal(missing.study_without_media, true);
  assert.equal(mismatch.media_state, 'sha-mismatch');
  assert.equal(mismatch.next_action, 'inspect-recovery');
  assert.equal(codec.media_state, 'unsupported-codec');
});

test('stale table and draft correction route to explicit immutable-authority actions', () => {
  const [stale, draft] = Core.buildCatalog([
    material({ material_id: 'stale', table_bound_caption_revision_id: 'caption-3' }),
    material({ material_id: 'draft', caption_draft_present: true }),
  ], [], {});
  assert.equal(stale.table_state, 'stale');
  assert.equal(stale.next_action, 'create-table-revision');
  assert.equal(draft.caption_state, 'draft');
  assert.equal(draft.next_action, 'continue-correction');
});

test('delete/export safety retains referenced canon and never claims an external file was deleted', () => {
  const blocked = Core.buildDeletePlan({ referenced_count: 2, reused_count: 1, created_count: 5, external_artifact_known: true });
  const safe = Core.buildDeletePlan({ referenced_count: 0, reused_count: 2, created_count: 3, external_artifact_known: true });
  assert.equal(blocked.can_delete, false);
  assert.equal(blocked.next_action, 'export-before-delete');
  assert.equal(safe.delete_created_count, 3);
  assert.equal(safe.retain_count, 2);
  assert.equal(safe.external_files_deleted, false);
});

test('source-state descriptor excludes mutable display text and is stable across ordering', async () => {
  const a = await Core.sourceStateHash({ portable_scope_id: 'scope', caption_sha256: H('a'), table_content_sha256: H('b'), table_mapping_sha256: H('c'), media_sha256: H('d'), title: 'one' });
  const b = await Core.sourceStateHash({ title: 'two', media_sha256: H('d'), table_mapping_sha256: H('c'), table_content_sha256: H('b'), caption_sha256: H('a'), portable_scope_id: 'scope' });
  assert.equal(a, b);
});
