'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const initSqlJs=require('sql.js');
const Core=require('../public/js/lexical-resolution-core.js'); const Repository=require('../public/js/lexical-resolution-repository.js');
let SQL; test.before(async()=>{SQL=await initSqlJs();});
async function harness(){ const {MIGRATIONS}=await import('../public/db/migrations.js'); assert.equal(MIGRATIONS.length,51); const db=new SQL.Database(); db.run('PRAGMA foreign_keys=ON; CREATE TABLE texts(id TEXT PRIMARY KEY); CREATE TABLE sentences(id TEXT PRIMARY KEY,text_id TEXT);'); db.run(MIGRATIONS[50]); db.run("INSERT INTO texts VALUES ('t'); INSERT INTO sentences VALUES ('s','t');"); const rows=(sql,p=[])=>{const st=db.prepare(sql);st.bind(p);const out=[];while(st.step())out.push(st.getAsObject());st.free();return out;}; const adapter={dbQuery:async(s,p)=>rows(s,p),dbRun:async(s,p)=>{const st=db.prepare(s);st.run(p||[]);st.free();return{changes:db.getRowsModified()};},execRaw:async(s)=>db.run(s)}; return{db,rows,repo:Repository.createRepository(adapter,Core)}; }
function ev(id='e1',extra={}){return{id,occurrence_id:'lpro:t:s:0',text_id:'t',sentence_id:'s',word_offset:0,text_key:'tk',order_index:0,surface_norm:'נטע',source_anchor:'sha256:a',action:'confirm_candidate',chosen_analysis:{lemma:'נטע',lp_pos:'propernoun'},candidate_fingerprint:'sha256:c',morph_model_version:'m1',actor_kind:'owner',batch_id:'b1',created_at:'2026-09-04T00:00:00Z',...extra};}
test('migration 51 creates constrained append-only event storage',async()=>{const h=await harness();assert.equal(h.rows("SELECT name FROM sqlite_master WHERE type='table' AND name='lexical_resolution_events'").length,1);assert.throws(()=>h.db.run("INSERT INTO lexical_resolution_events(id,occurrence_id,text_id,sentence_id,word_offset,text_key,order_index,surface_norm,source_anchor,action,candidate_fingerprint,actor_kind,created_at) VALUES('x','o','t','s',0,'tk',0,'x','a','invent','c','owner','z')"));});
test('append is idempotent but rejects same id with different content',async()=>{const h=await harness();assert.equal((await h.repo.append(ev())).inserted,true);assert.equal((await h.repo.append(ev())).inserted,false);await assert.rejects(()=>h.repo.append(ev('e1',{note:'different'})),/LEXICAL_EVENT_ID_COLLISION/);assert.equal((await h.repo.listForText('t')).length,1);});
test('batch is exact, transactional and requires one batch id',async()=>{const h=await harness();const two=ev('e2',{occurrence_id:'lpro:t:s:1',word_offset:1});await h.repo.appendBatch([ev(),two]);assert.equal((await h.repo.listForText('t')).length,2);await assert.rejects(()=>h.repo.appendBatch([ev('e3'),ev('e4',{batch_id:'other',occurrence_id:'o4'})]),/LEXICAL_BATCH_ID_REQUIRED/);assert.equal((await h.repo.listForText('t')).length,2);});
test('a collision in the middle of a batch rolls back earlier inserts',async()=>{const h=await harness();await h.repo.append(ev());const before=(await h.repo.listForText('t')).length;await assert.rejects(()=>h.repo.appendBatch([ev('e3',{occurrence_id:'o3',word_offset:1}),ev('e1',{occurrence_id:'o4',word_offset:2,note:'collision'})]),/LEXICAL_EVENT_ID_COLLISION/);assert.equal((await h.repo.listForText('t')).length,before);});
