'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const sqlite3 = require('sqlite3');
const C = require('../public/js/mediatheque-core');
const ROOT = path.resolve(__dirname, '..');
const exec = (db, sql) => new Promise((yes, no) => db.exec(sql, e => e ? no(e) : yes()));
const query = (db, sql, params = []) => new Promise((yes, no) => db.all(sql, params, (e, rows) => e ? no(e) : yes(rows)));
test('personal CAS and undo preserve content and reject stale updates', async t => {
  const { createRepository } = require('../public/js/mediatheque-local-repository');
  const { MEDIATHEQUE_SCHEMA_SQL: SCHEMA_SQL } = await import('../public/db/migrations.js');
  const db = new sqlite3.Database(':memory:'); t.after(() => new Promise(r => db.close(r)));
  await exec(db, SCHEMA_SQL + "CREATE TABLE review_log(value TEXT); INSERT INTO review_log VALUES('unchanged');");
  const repo = createRepository({ query: (sql, params) => query(db, sql, params) });
  const initial = await repo.load(); assert.equal(initial.revision, 0);
  const changed = C.command(initial.structure, { type: 'category.create', id: 'cat', title: 'История' });
  const first = await repo.save(changed, 0); assert.equal(first.revision, 1);
  await assert.rejects(repo.save(C.empty(), 0), /CONFLICT/);
  const undone = await repo.undo(1); assert.deepEqual(undone.structure, C.empty());
  assert.deepEqual(await query(db, 'SELECT * FROM review_log'), [{ value: 'unchanged' }]);
});
test('public editorial drafts, atomic publication, rollback and owner-only authorization', async t => {
  const db = new sqlite3.Database(':memory:'); t.after(() => new Promise(r => db.close(r)));
  for (const file of ['020_identity.sql', '063_publication_domain.sql', '067_mediatheque_structure.sql'])
    await exec(db, fs.readFileSync(path.join(ROOT, 'migrations', file), 'utf8'));
  await exec(db, "INSERT INTO users(id,role) VALUES('owner','owner'),('member','member');");
  const { createPublicationRepo } = require('../db/publicationRepo');
  const repo = createPublicationRepo({ db }), owner = { id: 'owner', role: 'owner' }, member = { id: 'member', role: 'member' };
  await assert.rejects(repo.getMediathequeDraft(member), /PUBLISHER_FORBIDDEN/);
  let draft = await repo.getMediathequeDraft(owner);
  let state = C.command(draft.structure, { type: 'category.create', id: 'science', title: 'Наука' });
  const one = await repo.saveMediathequeDraft(owner, { structure: state, expectedVersion: 0 }, { idempotencyKey: 'save-1' });
  assert.equal(one.revision, 1);
  assert.equal((await repo.getPublicMediatheque()).structure.categories.length, 0);
  await assert.rejects(repo.saveMediathequeDraft(owner, { structure: state, expectedVersion: 0 }, { idempotencyKey: 'stale' }), /CONFLICT/);
  const published = await repo.publishMediatheque(owner, { expectedVersion: 1 }, { idempotencyKey: 'publish-1' });
  assert.deepEqual(await repo.publishMediatheque(owner, { expectedVersion: 1 }, { idempotencyKey: 'publish-1' }), published);
  assert.equal((await repo.getPublicMediatheque()).structure.categories[0].title, 'Наука');
  state = C.command(state, { type: 'category.update', id: 'science', title: 'Космос' });
  await repo.saveMediathequeDraft(owner, { structure: state, expectedVersion: 1 }, { idempotencyKey: 'save-2' });
  assert.equal((await repo.getPublicMediatheque()).structure.categories[0].title, 'Наука');
  const second = await repo.publishMediatheque(owner, { expectedVersion: 2, expectedEdition: published.edition_id }, { idempotencyKey: 'publish-2' });
  await assert.rejects(repo.rollbackMediatheque(owner, { editionId: published.edition_id, expectedVersion: 2, expectedEdition: published.edition_id }, { idempotencyKey: 'stale-pointer' }), /CONFLICT/);
  await repo.rollbackMediatheque(owner, { editionId: published.edition_id, expectedVersion: 2, expectedEdition: second.edition_id }, { idempotencyKey: 'rollback' });
  assert.equal((await repo.getPublicMediatheque()).structure.categories[0].title, 'Наука');
  await assert.rejects(exec(db, "UPDATE publication_mediatheque_editions SET structure_json='{}'"), /immutable/i);
  const privateDoc = C.command(C.empty(), { type: 'reference.save', references: [{ kind: 'personal', textKey: 'secret' }] });
  await assert.rejects(repo.saveMediathequeDraft(owner, { structure: privateDoc, expectedVersion: 2 }, { idempotencyKey: 'private' }), /PRIVATE_REFERENCE/);
});
