"""Compose the Israel Elections 2026 stage skyline (art/worlds/israel-elections-2026/skyline.px).

Hand-drawn stamps (below) are placed on a periodic hill line so the 160x24 frame tiles seamlessly
left-to-right. Re-run after editing a stamp:  python scripts/worlds/compose-elections-skyline.py
Two frames: `day` (light UI) and `night` (dark UI) share geometry; only the palette mapping differs.
Nothing religious, no party colours, no lettering: billboards are deliberately blank.
"""
import math
import pathlib

W, H = 160, 24
ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "art" / "worlds" / "israel-elections-2026" / "skyline.px"

HOUSE = [
    "oooooooooooooo",
    "osssssssssssSo",
    "osswsswsswssSo",
    "osswsswsswssSo",
    "ossssssssssSSo",
    "osswsswsswssSo",
    "osswsswsswssSo",
    "osssssswwsssSo",
    "osssssswwsssSo",
]
TALL_HOUSE = [
    "oooooooooo",
    "osssssssSo",
    "oswswswsSo",
    "oswswswsSo",
    "osssssssSo",
    "oswswswsSo",
    "oswswswsSo",
    "osssssssSo",
    "oswswswsSo",
    "oswswswsSo",
    "ossswwssSo",
    "ossswwssSo",
]
PARLIAMENT = [
    "oooooooooooooooooooooooooooooo",
    "oSSSSSSSSSSSSSSSSSSSSSSSSSSSSo",
    "o" + "s" * 28 + "o",
    "o" + "sw" * 14 + "o",
    "o" + "sw" * 14 + "o",
    "o" + "sw" * 14 + "o",
    "o" + "sw" * 14 + "o",
    "o" + "sw" * 14 + "o",
    "o" + "s" * 28 + "o",
    "o" * 30,
]
CYPRESS = [
    "..t..",
    ".ttt.",
    ".ttT.",
    ".ttT.",
    "tttTT",
    "tttTT",
    ".ttT.",
    ".ttT.",
    ".ttT.",
    "..o..",
    "..o..",
]
BILLBOARD = [
    "oooooooooooooooo",
    "oppppppppppppppo",
    "opbbbbbbbbbbbbpo",
    "oppppppppppppppo",
    "opqqqqqqqqqqqqpo",
    "oppppppppppppppo",
    "opqqqqqqqqpppppo",
    "oppppppppppppppo",
    "oooooooooooooooo",
    ".....o....o.....",
    ".....o....o.....",
]

for name, stamp in [("HOUSE", HOUSE), ("TALL_HOUSE", TALL_HOUSE), ("PARLIAMENT", PARLIAMENT),
                    ("CYPRESS", CYPRESS), ("BILLBOARD", BILLBOARD)]:
    assert len({len(r) for r in stamp}) == 1, name


def hill(x):
    # Two periodic waves (periods 160 and 80) keep the tile seamless.
    return 5 + round(1.6 * math.sin(2 * math.pi * x / W) + 0.8 * math.sin(2 * math.pi * x / 80 + 1.1))


grid = [["." for _ in range(W)] for _ in range(H)]
for x in range(W):
    top = H - hill(x)
    for y in range(top, H):
        grid[y][x] = "h" if y > top else "H"
for x in range(W):
    grid[H - 1][x] = "g"

# Bunting: a sagging string with alternating tchelet/white pennants (periodic, 20px).
for x in range(W):
    y = 1 + round(1.5 * (1 - math.cos(2 * math.pi * (x % 40) / 40)) / 2)
    grid[y][x] = "o"
    if x % 5 == 2:
        grid[y + 1][x] = "b" if (x // 5) % 2 == 0 else "p"
        grid[y + 2][x] = "b" if (x // 5) % 2 == 0 else "p"


def stamp(art, x, ground=H - 1):
    top = ground - len(art)
    for dy, row in enumerate(art):
        for dx, ch in enumerate(row):
            if ch != ".":
                grid[top + dy][x + dx] = ch


# Placement: nothing crosses the tile edge (x + width <= W).
stamp(CYPRESS, 3)
stamp(HOUSE, 9)
stamp(TALL_HOUSE, 24)
stamp(BILLBOARD, 38)
stamp(CYPRESS, 56)
stamp(PARLIAMENT, 64)
stamp(CYPRESS, 96)
stamp(HOUSE, 103)
stamp(BILLBOARD, 119)
stamp(TALL_HOUSE, 138)
stamp(CYPRESS, 150)

rows = ["".join(r) for r in grid]
assert all(len(r) == W for r in rows)

HEADER = """@split
# Stage skyline for Israel Elections 2026 — GENERATED by scripts/worlds/compose-elections-skyline.py
# from hand-drawn stamps; edit the stamps there, not this file. Tiles horizontally (period 160).
# day = light UI palette, night = dark UI palette; geometry identical.
. transparent
o #8a7456
s #e3d5b3
S #c4ae84
w #7b6a8f
t #4f7a52
T #365a3c
h #c9cf9e
H #b3bb86
g #9aa36f
b #1b4fb8
p #f7f4ea
q #c9c3b1
"""
NIGHT = {"o": "O", "s": "N", "S": "M", "w": "L", "t": "E", "T": "F", "h": "J", "H": "K", "g": "G", "b": "B", "p": "P", "q": "Q"}
NIGHT_PALETTE = """O #0d1122
N #3b4262
M #2c3150
L #f2c86a
E #22403a
F #182e2a
J #1f2a45
K #26334f
G #18213a
B #5d86e0
P #4a5378
Q #3a4266
"""
night_rows = ["".join(NIGHT.get(c, c) for c in r) for r in rows]
text = HEADER + NIGHT_PALETTE + f"\n@frame day {W}x{H} anchor=0,{H - 1}\n" + "\n".join(rows) + \
    f"\n\n@frame night {W}x{H} anchor=0,{H - 1}\n" + "\n".join(night_rows) + "\n"
OUT.write_text(text, encoding="utf-8")
print("wrote", OUT.relative_to(ROOT))
