"""Reproducible product helper, derived from the exact owner-qualified engine ZIP."""
from __future__ import annotations
import argparse
import base64
import hashlib
import io
import json
from pathlib import Path
import subprocess
import zipfile

ROOT = Path(__file__).resolve().parents[2]
PROBE_HASH = '0744253ad45912fd53f641b10f9832e68511641f211d1bf82ae8151d6f7e4282'
SOURCE = ROOT / 'scripts/premium/iphone-downloader'
ENGINE = ('__init__.py', 'jobs.py', 'planner.py', 'receipts.py', 'media_verify.py')


def package_files():
    archive = ROOT / 'public/downloads/linguistpro-iphone-probe-0744253a.zip'
    data = archive.read_bytes()
    if hashlib.sha256(data).hexdigest() != PROBE_HASH:
        raise ValueError('OWNER_QUALIFIED_ENGINE_HASH_MISMATCH')
    files = {name: (SOURCE / name).read_bytes() for name in ('__main__.py', 'runner.py')}
    with zipfile.ZipFile(io.BytesIO(data)) as probe:
        prefix = 'LinguistPro-iPhone-probe/'
        files['probe.py'] = probe.read(prefix + 'run.py')
        for name in ENGINE:
            files['acquisition_service/' + name] = probe.read(prefix + 'acquisition_service/' + name)
    files['ui.js'] = (SOURCE / 'native-ui.js').read_bytes()
    files['ui.css'] = (ROOT / 'public/css/iphone-downloader.css').read_bytes()
    # These are repository-controlled locale modules, not user/provider input.
    command = "const fs=require('fs'),vm=require('vm'),p=require('path'); const out={}; for(const lang of ['ru','en','he']){const c={window:{}};vm.runInNewContext(fs.readFileSync(p.join(process.argv[1],lang+'.js'),'utf8'),c);out[lang]=c.window.I18N_LOCALES[lang].phoneDownload;}process.stdout.write(JSON.stringify(out));"
    copy = json.loads(subprocess.check_output(['node', '-e', command, str(ROOT / 'public/i18n/locales')], text=True, encoding='utf-8'))
    if not copy['ru'] or any(set(copy[lang]) != set(copy['ru']) for lang in ('en', 'he')):
        raise ValueError('NATIVE_COPY_PARITY_FAILED')
    files['copy.json'] = (json.dumps(copy, ensure_ascii=True, sort_keys=True) + '\n').encode()
    return files


def build():
    files = package_files()
    manifest = {'schema': 'lp-iphone-downloader-package-v1', 'engine_probe_sha256': PROBE_HASH,
                'files': {name: hashlib.sha256(data).hexdigest() for name, data in sorted(files.items())}}
    files['manifest.json'] = (json.dumps(manifest, sort_keys=True, indent=2) + '\n').encode()
    result = io.BytesIO()
    with zipfile.ZipFile(result, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for name, data in sorted(files.items()):
            entry = zipfile.ZipInfo(name, (2026, 9, 8, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.external_attr = 0o100644 << 16
            archive.writestr(entry, data)
    data = result.getvalue()
    digest = hashlib.sha256(data).hexdigest()
    name = 'iphone-downloader-' + digest[:16] + '.pyz'
    path = ROOT / 'public/downloads' / name
    if path.exists() and path.read_bytes() != data:
        raise ValueError('IMMUTABLE_ARTIFACT_CONFLICT')
    path.write_bytes(data)
    bootstrap = (SOURCE / 'bootstrap.py').read_text(encoding='utf-8')
    bootstrap = bootstrap.replace('__SHORT_HASH__', digest[:16]).replace('__PACKAGE_HASH__', digest)
    # Drop comments/blank lines only; this is a deterministic generated launch asset.
    bootstrap = '\n'.join(line for line in bootstrap.splitlines() if line.strip() and not line.lstrip().startswith('#'))
    release = {'v': 1, 'sha256': digest, 'bytes': len(data), 'path': '/downloads/' + name,
               'bootstrap': base64.b64encode(bootstrap.encode()).decode()}
    js = '/* Generated by build-iphone-downloader.py; do not edit. */\nwindow.IPhoneDownloaderRelease = ' + json.dumps(release, separators=(',', ':')) + ';\n'
    (ROOT / 'public/js/iphone-downloader-release.js').write_text(js, encoding='utf-8', newline='\n')
    print(json.dumps({key: value for key, value in release.items() if key != 'bootstrap'}))
    return release


if __name__ == '__main__':
    argparse.ArgumentParser(description=__doc__).parse_args()
    build()
