"use strict";

const {getDb}=require("./sqlite");
const {withTxnLock}=require("./txnLock");
const C=require("../agent/evidence/contracts");
const run=(db,sql,p=[])=>new Promise((res,rej)=>db.run(sql,p,function(e){e?rej(e):res(this);}));
const get=(db,sql,p=[])=>new Promise((res,rej)=>db.get(sql,p,(e,r)=>e?rej(e):res(r||null)));
const all=(db,sql,p=[])=>new Promise((res,rej)=>db.all(sql,p,(e,r)=>e?rej(e):res(r||[])));
const now=()=>new Date().toISOString();
const plus=(iso,days)=>new Date(Date.parse(iso)+days*86400000).toISOString();
const json=(v)=>C.canonicalJson(v);
const parse=(s,d)=>C.parseJson(s,d);

async function currentConsent(userId,key){const db=getDb();const r=await get(db,`SELECT id,consent_version,granted,created_at FROM consent_records WHERE user_id=? AND consent_key=? ORDER BY created_at DESC,id DESC LIMIT 1`,[userId,key]);return r&&Number(r.granted)===1?r:null;}
function parseRequest(row){if(!row)return null;return {...row,source_a:parse(row.source_a_json,{}),source_b:parse(row.source_b_json,{}),stimulus:parse(row.stimulus_json,{}),expected:parse(row.expected_json,{})};}
async function loadRequest(userId,id){const db=getDb();return parseRequest(await get(db,`SELECT r.*,h.item_key,h.claim_code,h.status hypothesis_status,h.observation_id FROM f2_requests r JOIN f2_hypotheses h ON h.id=r.hypothesis_id AND h.user_id=r.user_id WHERE r.user_id=? AND r.id=?`,[userId,String(id)]));}
async function counts(userId){const db=getDb();const r=await get(db,`SELECT COUNT(*) total,SUM(CASE WHEN state IN ('PENDING','OFFERED','ACCEPTED','DEFERRED','SUBMITTED') THEN 1 ELSE 0 END) open,SUM(CASE WHEN created_at>=? THEN 1 ELSE 0 END) created_today FROM f2_requests WHERE user_id=?`,[new Date().toISOString().slice(0,10)+"T00:00:00.000Z",userId]);return {total:Number(r&&r.total)||0,open:Number(r&&r.open)||0,created_today:Number(r&&r.created_today)||0};}

async function createChain(userId,input){const db=getDb();return withTxnLock(async()=>{await run(db,"BEGIN IMMEDIATE");try{
  const cnt=await counts(userId);if(cnt.open>=2)throw new Error("F2_OPEN_LIMIT");
  const liveObs=await get(db,`SELECT COUNT(*) c FROM f2_observations WHERE user_id=? AND status IN ('ELIGIBLE','SUPPRESSED') AND expires_at>?`,[userId,now()]);if(Number(liveObs&&liveObs.c)>=20)throw new Error("F2_OBSERVATION_LIMIT");
  const liveHyp=await get(db,`SELECT COUNT(*) c FROM f2_hypotheses WHERE user_id=? AND status IN ('ELIGIBLE','OFFERED','TESTED','SUPPRESSED') AND expires_at>?`,[userId,now()]);if(Number(liveHyp&&liveHyp.c)>=10)throw new Error("F2_HYPOTHESIS_LIMIT");
  const t=now(),obsId=C.opaque("f2obs_"),hypId=C.opaque("f2hyp_"),reqId=C.opaque("f2req_");
  await run(db,`INSERT INTO f2_observations (id,user_id,construct_id,item_key,authority_class,canonical_event_refs_json,source_a_json,predicate_version,status,reason_code,observed_at,created_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,[obsId,userId,input.construct_id,input.item_key,input.authority_class,json(input.canonical_event_refs),json(input.source_a),input.predicate_version,"ELIGIBLE",input.reason_code||null,input.observed_at,t,plus(t,input.construct_id===C.CONSTRUCTS.B1?60:30)]);
  await run(db,`INSERT INTO f2_hypotheses (id,user_id,observation_id,construct_id,item_key,claim_code,confidence_band,status,rule_version,consent_snapshot_ref,created_at,updated_at,expires_at) VALUES (?,?,?,?,?,?,'UNVERIFIED','ELIGIBLE',?,?,?,?,?)`,[hypId,userId,obsId,input.construct_id,input.item_key,input.claim_code,input.predicate_version,input.consent_snapshot_ref,t,t,plus(t,14)]);
  const expectedJson=json(input.expected),expectedDigest=C.digest(userId,input.expected);
  await run(db,`INSERT INTO f2_requests (id,user_id,hypothesis_id,construct_id,request_kind,state,source_a_json,source_b_json,stimulus_json,expected_json,expected_digest,schema_version,policy_version,predicate_version,not_before,created_at,updated_at,expires_at) VALUES (?,?,?,?,?,'PENDING',?,?,?,?,?,?,?,?,?,?,?,?)`,[reqId,userId,hypId,input.construct_id,input.request_kind,json(input.source_a),json(input.source_b),json(input.stimulus),expectedJson,expectedDigest,C.SCHEMA_VERSION,C.POLICY_VERSION,input.predicate_version,input.not_before,t,t,plus(t,7)]);
  for(const s of input.sources||[])await run(db,`INSERT INTO f2_source_links (id,user_id,artifact_type,artifact_id,source_kind,relation_kind,source_ref,source_revision_ref,authority_class,anchor_json,keyed_digest,source_status,created_at) VALUES (?,?, 'REQUEST',?,?,?,?,?,?,?,?, 'AVAILABLE',?)`,[C.opaque("f2src_"),userId,reqId,s.source_kind,s.relation_kind,s.source_ref,s.source_revision_ref||null,s.authority_class,json(s.anchor||{}),s.keyed_digest||null,t]);
  await auditTx(db,userId,"REQUEST",reqId,"CREATE","DETERMINISTIC_POLICY",null,"1",input.reason_code||"ELIGIBLE");
  await run(db,"COMMIT");return loadRequest(userId,reqId);
}catch(e){try{await run(db,"ROLLBACK");}catch(_){}throw e;}});}

async function auditTx(db,userId,type,id,action,actor,prior,next,reason,terminal=null){const t=now();await run(db,`INSERT INTO f2_audit_events (id,user_id,artifact_type,artifact_id,action,actor_class,prior_revision,new_revision,reason_code,terminal_code,created_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[C.opaque("f2aud_"),userId,type,id,action,actor,prior,next,reason||null,terminal,t,plus(t,30)]);}
async function writeQueryReceipt(userId,x){const db=getDb(),t=now(),id=C.opaque("f2q_");await run(db,`INSERT INTO f2_context_queries (id,user_id,purpose,surface,policy_version,consent_snapshot_ref,eligible_count,selected_ids_json,exclusion_counts_json,terminal_code,created_at,expires_at) VALUES (?,? ,?,'pwa',?,?,?,?,?,?,?,?)`,[id,userId,x.purpose,C.POLICY_VERSION,x.consent_snapshot_ref,Math.min(100,Number(x.eligible_count)||0),json((x.selected_ids||[]).slice(0,2)),json(x.exclusions||{}),String(x.terminal_code||"OK"),t,plus(t,30)]);return id;}

async function list(userId,{state,limit,before}={}){const db=getDb();let where="r.user_id=?",p=[userId];if(state){where+=" AND r.state=?";p.push(String(state));}if(before){where+=" AND r.updated_at<?";p.push(String(before));}p.push(Math.max(1,Math.min(20,Number(limit)||5)));const rows=await all(db,`SELECT r.*,h.item_key,h.claim_code,h.status hypothesis_status,o.authority_class FROM f2_requests r JOIN f2_hypotheses h ON h.id=r.hypothesis_id JOIN f2_observations o ON o.id=h.observation_id WHERE ${where} ORDER BY r.updated_at DESC,r.id DESC LIMIT ?`,p);const out=[];for(const row of rows){const item=parseRequest(row);item.attempt=await get(db,`SELECT id,state,input_mode,assistance_codes_json,mnar_code,created_at,finalized_at FROM f2_attempts WHERE user_id=? AND request_id=?`,[userId,row.id]);item.evaluation=await get(db,`SELECT id,evaluator_kind,evaluator_version,rubric_version,normalizer_version,verdict,confidence,uncertainty_codes_json,rationale_codes_json,status,created_at FROM f2_evaluations WHERE user_id=? AND attempt_id=(SELECT id FROM f2_attempts WHERE user_id=? AND request_id=?)`,[userId,userId,row.id]);item.decision=await get(db,`SELECT id,decision_rule_version,decision_code,reason_codes_json,status,created_at FROM f2_shadow_decisions WHERE user_id=? AND hypothesis_id=? AND status IN ('VALID','DISPUTED') ORDER BY created_at DESC LIMIT 1`,[userId,row.hypothesis_id]);delete item.expected_json;delete item.expected;out.push(item);}return {items:out};}

async function offer(userId,consentRef){const db=getDb(),t=now();const rows=await all(db,`SELECT * FROM f2_requests WHERE user_id=? AND state IN ('PENDING','DEFERRED') AND not_before<=? AND expires_at>? ORDER BY created_at,id LIMIT 20`,[userId,t,t]);const selected=rows[0]||null;if(selected){await run(db,`UPDATE f2_requests SET state='OFFERED',offered_at=COALESCE(offered_at,?),updated_at=? WHERE user_id=? AND id=? AND state IN ('PENDING','DEFERRED')`,[t,t,userId,selected.id]);await run(db,`UPDATE f2_hypotheses SET status='OFFERED',updated_at=? WHERE user_id=? AND id=? AND status='ELIGIBLE'`,[t,userId,selected.hypothesis_id]);}await writeQueryReceipt(userId,{purpose:"F2_OFFER",consent_snapshot_ref:consentRef,eligible_count:rows.length,selected_ids:selected?[selected.id]:[],terminal_code:selected?"OFFERED":"NONE"});if(!selected)return null;const out=parseRequest({...selected,state:"OFFERED",offered_at:selected.offered_at||t,updated_at:t});delete out.expected;delete out.expected_json;delete out.expected_digest;return out;}

const TRANSITIONS={ACCEPT:new Set(["OFFERED"]),SKIP:new Set(["PENDING","OFFERED","ACCEPTED","DEFERRED"]),DEFER:new Set(["PENDING","OFFERED","ACCEPTED"]),SUPPRESS:new Set(["PENDING","OFFERED","ACCEPTED","DEFERRED"]),UNSUPPRESS:new Set(["SUPPRESSED"]),DISPUTE:new Set(["COMPLETED"]),ANNUL:new Set(["COMPLETED"])};
async function action(userId,id,action,input={}){const db=getDb();return withTxnLock(async()=>{await run(db,"BEGIN IMMEDIATE");try{const row=await get(db,`SELECT * FROM f2_requests WHERE user_id=? AND id=?`,[userId,id]);if(!row)throw new Error("F2_NOT_FOUND");if(action==="DELETE"){await deleteChainTx(db,userId,row.hypothesis_id,"USER_DELETE");await run(db,"COMMIT");return {deleted:true};}if(!TRANSITIONS[action]||!TRANSITIONS[action].has(row.state))throw new Error("STATE_CONFLICT");const t=now();let next=row.state,notBefore=row.not_before,defer=row.defer_count,terminal=null;
  if(action==="ACCEPT")next="ACCEPTED";
  if(action==="SKIP"){next="SKIPPED";terminal=t;await upsertMnarTx(db,userId,row.id,"SKIPPED","USER_SKIP",t);await run(db,`UPDATE f2_hypotheses SET status='EXPIRED',updated_at=? WHERE user_id=? AND id=?`,[t,userId,row.hypothesis_id]);}
  if(action==="DEFER"){if(defer>=2)throw new Error("F2_DEFER_LIMIT");defer++;notBefore=new Date(Math.min(Date.parse(row.expires_at)-1000,Date.parse(t)+86400000)).toISOString();next="DEFERRED";await upsertMnarTx(db,userId,row.id,"DEFERRED","USER_DEFER",t);}
  if(action==="SUPPRESS")next="SUPPRESSED";
  if(action==="UNSUPPRESS")next="PENDING";
  if(action==="DISPUTE"){next="COMPLETED";await run(db,`UPDATE f2_evaluations SET status='DISPUTED' WHERE user_id=? AND attempt_id=(SELECT id FROM f2_attempts WHERE request_id=? AND user_id=?)`,[userId,row.id,userId]);await run(db,`UPDATE f2_shadow_decisions SET status='DISPUTED' WHERE user_id=? AND hypothesis_id=? AND status='VALID'`,[userId,row.hypothesis_id]);}
  if(action==="ANNUL"){next="ANNULLED";terminal=t;await run(db,`UPDATE f2_evaluations SET status='ANNULLED' WHERE user_id=? AND attempt_id=(SELECT id FROM f2_attempts WHERE request_id=? AND user_id=?)`,[userId,row.id,userId]);await run(db,`UPDATE f2_shadow_decisions SET status='ANNULLED' WHERE user_id=? AND hypothesis_id=?`,[userId,row.hypothesis_id]);await run(db,`UPDATE f2_hypotheses SET status='ANNULLED',updated_at=? WHERE user_id=? AND id=?`,[t,userId,row.hypothesis_id]);}
  if(action==="ACCEPT")await run(db,`UPDATE f2_hypotheses SET status='TESTED',updated_at=? WHERE user_id=? AND id=?`,[t,userId,row.hypothesis_id]);
  if(action==="SUPPRESS")await run(db,`UPDATE f2_hypotheses SET status='SUPPRESSED',updated_at=? WHERE user_id=? AND id=?`,[t,userId,row.hypothesis_id]);
  if(action==="UNSUPPRESS")await run(db,`UPDATE f2_hypotheses SET status='ELIGIBLE',updated_at=? WHERE user_id=? AND id=?`,[t,userId,row.hypothesis_id]);
  await run(db,`UPDATE f2_requests SET state=?,not_before=?,defer_count=?,accepted_at=CASE WHEN ?='ACCEPTED' THEN COALESCE(accepted_at,?) ELSE accepted_at END,terminal_at=COALESCE(?,terminal_at),updated_at=? WHERE user_id=? AND id=?`,[next,notBefore,defer,next,t,terminal,t,userId,row.id]);
  await auditTx(db,userId,"REQUEST",row.id,action,"USER",row.state,next,input.reason_code||null,terminal?next:null);await run(db,"COMMIT");return loadRequest(userId,row.id);
}catch(e){try{await run(db,"ROLLBACK");}catch(_){}throw e;}});}

async function insertMnarTx(db,userId,requestId,state,code,t){await run(db,`INSERT INTO f2_attempts (id,user_id,request_id,state,assistance_codes_json,answer_json,answer_digest,mnar_code,created_at,finalized_at,expires_at) VALUES (?,?,?,?,'[]',NULL,NULL,?,?,?,?)`,[C.opaque("f2att_"),userId,requestId,state,code,t,t,plus(t,30)]);}
async function upsertMnarTx(db,userId,requestId,state,code,t){const old=await get(db,`SELECT id FROM f2_attempts WHERE user_id=? AND request_id=?`,[userId,requestId]);if(old)await run(db,`UPDATE f2_attempts SET state=?,mnar_code=?,answer_json=NULL,answer_digest=NULL,finalized_at=?,expires_at=?,revision=2 WHERE user_id=? AND request_id=?`,[state,code,t,plus(t,30),userId,requestId]);else await insertMnarTx(db,userId,requestId,state,code,t);}
async function submit(userId,id,attempt,evaluation,decision){const db=getDb();return withTxnLock(async()=>{await run(db,"BEGIN IMMEDIATE");try{const row=await get(db,`SELECT * FROM f2_requests WHERE user_id=? AND id=?`,[userId,id]);if(!row)throw new Error("F2_NOT_FOUND");if(row.state!=="ACCEPTED")throw new Error("STATE_CONFLICT");if(Date.parse(row.expires_at)<=Date.now())throw new Error("REQUEST_EXPIRED");const t=now(),eid=C.opaque("f2eval_"),did=C.opaque("f2dec_");let aid=C.opaque("f2att_");const answerObj={answer:attempt.answer||null,option_id:attempt.option_id||null};
  const deferred=await get(db,`SELECT id FROM f2_attempts WHERE user_id=? AND request_id=? AND state='DEFERRED'`,[userId,id]);
  if(deferred){aid=deferred.id;await run(db,`UPDATE f2_attempts SET state='SUBMITTED',input_mode=?,assistance_codes_json=?,answer_json=?,answer_digest=?,mnar_code=NULL,revision=2,finalized_at=?,expires_at=? WHERE user_id=? AND id=?`,[attempt.input_mode||null,json(attempt.assistance_codes||[]),json(answerObj),C.digest(userId,answerObj),t,plus(t,30),userId,aid]);}
  else await run(db,`INSERT INTO f2_attempts (id,user_id,request_id,state,input_mode,assistance_codes_json,answer_json,answer_digest,mnar_code,created_at,finalized_at,expires_at) VALUES (?,?,?,'SUBMITTED',?,?,?,?,NULL,?,?,?)`,[aid,userId,id,attempt.input_mode||null,json(attempt.assistance_codes||[]),json(answerObj),C.digest(userId,answerObj),t,t,plus(t,30)]);
  await run(db,`INSERT INTO f2_evaluations (id,user_id,attempt_id,evaluator_kind,evaluator_version,rubric_version,normalizer_version,input_digest,verdict,confidence,uncertainty_codes_json,rationale_codes_json,status,created_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,'VALID',?,?)`,[eid,userId,aid,evaluation.evaluator_kind,evaluation.evaluator_version,evaluation.rubric_version,evaluation.normalizer_version,C.digest(userId,{expected:row.expected_digest,answer:C.digest(userId,answerObj)}),evaluation.verdict,evaluation.confidence,json(evaluation.uncertainty_codes||[]),json(evaluation.rationale_codes||[]),t,plus(t,30)]);
  await run(db,`INSERT INTO f2_shadow_decisions (id,user_id,hypothesis_id,evaluation_id,decision_rule_version,decision_code,reason_codes_json,status,created_at,expires_at) VALUES (?,?,?,?,?,?,?,'VALID',?,?)`,[did,userId,row.hypothesis_id,eid,decision.decision_rule_version,decision.decision_code,json(decision.reason_codes||[]),t,plus(t,30)]);
  await run(db,`UPDATE f2_requests SET state='COMPLETED',updated_at=?,terminal_at=? WHERE user_id=? AND id=?`,[t,t,userId,id]);await run(db,`UPDATE f2_hypotheses SET status='RESOLVED_SHADOW',updated_at=? WHERE user_id=? AND id=?`,[t,userId,row.hypothesis_id]);await auditTx(db,userId,"REQUEST",id,"SUBMIT","USER",row.state,"COMPLETED",evaluation.verdict,"COMPLETED");await run(db,"COMMIT");return {attempt_id:aid,evaluation_id:eid,decision_id:did,verdict:evaluation.verdict,decision_code:decision.decision_code};
}catch(e){try{await run(db,"ROLLBACK");}catch(_){}throw e;}});}

async function deleteChainTx(db,userId,hypothesisId,reason){const row=await get(db,`SELECT observation_id FROM f2_hypotheses WHERE user_id=? AND id=?`,[userId,hypothesisId]);if(!row)throw new Error("F2_NOT_FOUND");const reqs=(await all(db,`SELECT id FROM f2_requests WHERE user_id=? AND hypothesis_id=?`,[userId,hypothesisId])).map(x=>String(x.id));const t=now();await run(db,`INSERT INTO f2_erasure_journal (user_id,chain_id,deleted_at,reason_code) VALUES (?,?,?,?)`,[userId,hypothesisId,t,reason]);for(const rid of reqs){await run(db,`DELETE FROM f2_context_queries WHERE user_id=? AND selected_ids_json LIKE ?`,[userId,`%${rid}%`]);await run(db,`DELETE FROM f2_source_links WHERE user_id=? AND artifact_id=?`,[userId,rid]);await run(db,`DELETE FROM f2_audit_events WHERE user_id=? AND artifact_id=?`,[userId,rid]);}await run(db,`DELETE FROM f2_source_links WHERE user_id=? AND artifact_id IN (?,?)`,[userId,hypothesisId,row.observation_id]);await run(db,`DELETE FROM f2_audit_events WHERE user_id=? AND artifact_id IN (?,?)`,[userId,hypothesisId,row.observation_id]);await run(db,`DELETE FROM f2_observations WHERE user_id=? AND id=?`,[userId,row.observation_id]);}
async function deleteAll(userId,reason="USER_DELETE_ALL",construct=null){const db=getDb();return withTxnLock(async()=>{await run(db,"BEGIN IMMEDIATE");try{const p=[userId];let w="user_id=?";if(construct){w+=" AND construct_id=?";p.push(construct);}const ids=(await all(db,`SELECT id FROM f2_hypotheses WHERE ${w}`,p)).map(r=>r.id);for(const id of ids)await deleteChainTx(db,userId,id,reason);if(!construct)await run(db,`DELETE FROM f2_context_queries WHERE user_id=?`,[userId]);await run(db,"COMMIT");return {deleted:ids.length};}catch(e){try{await run(db,"ROLLBACK");}catch(_){}throw e;}});}
async function exportEvidence(userId){const db=getDb();const tables=["f2_observations","f2_hypotheses","f2_requests","f2_attempts","f2_evaluations","f2_shadow_decisions","f2_source_links","f2_audit_events","f2_context_queries"];const out={schema_version:C.SCHEMA_VERSION,exported_at:now()};for(const table of tables){out[table]=await all(db,`SELECT * FROM ${table} WHERE user_id=? ORDER BY rowid`,[userId]);for(const row of out[table]){delete row.keyed_digest;delete row.expected_digest;delete row.answer_digest;if(table==="f2_requests")delete row.expected_json;}}out.erasures=await all(db,`SELECT chain_id,deleted_at,reason_code FROM f2_erasure_journal WHERE user_id=? ORDER BY deleted_at`,[userId]);return out;}
async function expireAndPurge(t=now()){let db;try{db=getDb();}catch(_){return {requests:0,content:0,queries:0,journal:0};}return withTxnLock(async()=>{await run(db,"BEGIN IMMEDIATE");try{const expired=await all(db,`SELECT id,user_id,hypothesis_id FROM f2_requests WHERE state IN ('PENDING','OFFERED','ACCEPTED','DEFERRED') AND expires_at<=?`,[t]);for(const x of expired){await upsertMnarTx(db,x.user_id,x.id,"EXPIRED","LIFECYCLE_EXPIRED",t);await run(db,`UPDATE f2_hypotheses SET status='EXPIRED',updated_at=? WHERE user_id=? AND id=?`,[t,x.user_id,x.hypothesis_id]);await auditTx(db,x.user_id,"REQUEST",x.id,"EXPIRE","SYSTEM_LIFECYCLE",null,"EXPIRED","TTL","EXPIRED");}const r=await run(db,`UPDATE f2_requests SET state='EXPIRED',terminal_at=?,updated_at=? WHERE state IN ('PENDING','OFFERED','ACCEPTED','DEFERRED') AND expires_at<=?`,[t,t,t]);const c=await run(db,`UPDATE f2_attempts SET answer_json=NULL WHERE answer_json IS NOT NULL AND expires_at<=?`,[t]);const q=await run(db,`DELETE FROM f2_context_queries WHERE expires_at<=?`,[t]);const a=await run(db,`DELETE FROM f2_audit_events WHERE expires_at<=?`,[t]);await run(db,"COMMIT");return {requests:r.changes,content:c.changes,queries:q.changes,audit:a.changes,journal:0};}catch(e){try{await run(db,"ROLLBACK");}catch(_){}throw e;}});}

module.exports={currentConsent,createChain,loadRequest,list,offer,action,submit,writeQueryReceipt,deleteAll,exportEvidence,expireAndPurge,counts};
