"use strict";
const C=require("./contracts");
function buildB1(obs,consentRef,now=new Date().toISOString()){
  return {...obs,claim_code:"H_B1_PRODUCTION_TRANSFER_UNVERIFIED",request_kind:"dictate_shadow_v1",reason_code:"B1_ELIGIBLE",consent_snapshot_ref:consentRef,not_before:now,source_b:{asset_kind:"dictate",pid:obs.form.pid},stimulus:{kind:"dictate_shadow_v1",audio_ref:`dictate:${obs.item_key}`},expected:{kind:"dictate_shadow_v1",surface:obs.form.written,vocalized:obs.form.vocalized,item_key:obs.item_key,ambiguous:false,homophone_risk:false},sources:[{source_kind:"CANONICAL_REVIEW_EVENT",relation_kind:"OBSERVED_FROM",source_ref:obs.canonical_event_refs[0],authority_class:"CANONICAL_PATTERN",anchor:{}},{source_kind:"AUDIO_ASSET",relation_kind:"TESTS_WITH",source_ref:`dictate:${obs.item_key}`,authority_class:"PUBLIC_ASSERTED",anchor:{}}]};
}
function buildB2(obs,target,consentRef){
  const sentence=String(target.sentence||"");const escaped=target.surface.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");const prompt=sentence.replace(new RegExp(escaped),"____");
  return {...obs,claim_code:"H_B2_READING_TRANSFER_UNVERIFIED",request_kind:"new_context_cloze_shadow_v1",reason_code:"B2_ELIGIBLE",consent_snapshot_ref:consentRef,not_before:C.plusMs(obs.observed_at,86400000),source_b:{corpus:target.corpus,work_id:target.work_id,text_key:target.text_key,order_index:target.order_index,revision:target.revision},stimulus:{kind:"new_context_cloze_shadow_v1",sentence:prompt,options:target.options.map(x=>({id:x.id,surface:x.surface}))},expected:{kind:"new_context_cloze_shadow_v1",item_key:obs.item_key,target_revision:target.revision,correct_option_id:target.correct_option_id,options:target.options},sources:[{source_kind:"CANONICAL_REVIEW_EVENT",relation_kind:"OBSERVED_FROM",source_ref:obs.canonical_event_refs[0],authority_class:"SELF_REPORTED_RETRIEVAL",anchor:{text_key:obs.source_a.text_key}},{source_kind:"PUBLIC_CORPUS_ANCHOR",relation_kind:"TESTS_WITH",source_ref:target.ref,source_revision_ref:target.revision,authority_class:"PUBLIC_ASSERTED",anchor:{work_id:target.work_id,text_key:target.text_key,order_index:target.order_index}}]};
}
module.exports={buildB1,buildB2};
