"use strict";
const C=require("./contracts");
const MAP=Object.freeze({
  CORRECT_UNASSISTED:"NO_EXTRA_TARGETED_PRACTICE",
  CORRECT_ASSISTED:"ONE_CONTEXTUAL_RETRIEVAL_CANDIDATE",
  NEAR_MISS:"ONE_CONTEXTUAL_RETRIEVAL_CANDIDATE",
  INCORRECT:"ONE_UNSUPPORTED_RETRIEVAL_CANDIDATE",
  CORRECT_NEW_CONTEXT:"TRANSFER_OBSERVED_ONCE_NO_ACTION",
  INCORRECT_NEW_CONTEXT:"ONE_CONTRASTIVE_CONTEXT_CANDIDATE",
  AMBIGUOUS:"INCONCLUSIVE",ABSTAIN:"INCONCLUSIVE",SOURCE_DRIFT:"INCONCLUSIVE",DISAGREEMENT:"INCONCLUSIVE",
});
function reduce(evaluation){const code=MAP[String(evaluation&&evaluation.verdict)]||"INCONCLUSIVE";return {decision_rule_version:C.DECISION_RULE_VERSION,decision_code:code,reason_codes:[String(evaluation&&evaluation.verdict||"MISSING_EVALUATION")]};}
module.exports={reduce,MAP};
