#!/usr/bin/env node
// scripts/research/validate-cli.js — Workstream A5 (v3.3.1).
//
// Standalone CLI wrapping research/validate.js. Useful for:
//   - Ulpan teachers / researchers preparing a payload before upload
//   - Smoke-checking JSONL archives at rest
//   - Pre-flighting fixtures generated by seed_research_fake_cohort.js
//
// Reads a JSON payload from a file path or stdin and prints either
// "OK" + a one-line summary OR a SchemaViolationError diagnostic
// (with --json for machine-readable output).
//
// Behavior:
//   - exit 0 = payload validates
//   - exit 3 = payload invalid (SchemaViolationError thrown)
//   - exit 2 = argv / IO error
//
// Usage:
//   node scripts/research/validate-cli.js <path>
//   node scripts/research/validate-cli.js < payload.json    # read from stdin
//   cat payload.json | node scripts/research/validate-cli.js
//   node scripts/research/validate-cli.js <path> --json     # machine-readable
//   node scripts/research/validate-cli.js --jsonl <path>    # validate every line

"use strict";

const fs = require("fs");
const path = require("path");

const { validatePayload, SchemaViolationError } = require("../../research/validate");

function parseArgs(argv) {
  const args = { _: [], json: false, jsonl: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--json") args.json = true;
    else if (a === "--jsonl") args.jsonl = true;
    else if (a === "--help" || a === "-h") args.help = true;
    else args._.push(a);
  }
  return args;
}

function readSource(args) {
  if (args._.length > 0) {
    const p = path.resolve(args._[0]);
    if (!fs.existsSync(p)) {
      console.error(`error: file not found — ${p}`);
      process.exit(2);
    }
    return fs.readFileSync(p, "utf8");
  }
  // stdin
  try { return fs.readFileSync(0, "utf8"); }
  catch (e) { console.error("error: failed to read stdin —", e.message); process.exit(2); }
}

function emitOk(asJson, summary) {
  if (asJson) {
    process.stdout.write(JSON.stringify({ ok: true, ...summary }) + "\n");
  } else {
    process.stdout.write(`OK · ${summary.lines || 1} payload(s) valid\n`);
    if (summary.format) process.stdout.write(`  format:           ${summary.format}\n`);
    if (summary.cohort_code) process.stdout.write(`  cohort_code:      ${summary.cohort_code}\n`);
    if (summary.consent_version) process.stdout.write(`  consent_version:  ${summary.consent_version}\n`);
    if (summary.upload_ts) process.stdout.write(`  upload_ts:        ${summary.upload_ts}\n`);
  }
}

function emitFail(asJson, err, lineNumber) {
  const diag = {
    ok: false,
    code: (err && err.code) || "UNKNOWN",
    field: (err && err.field) || "$",
    message: (err && err.message) || String(err),
    line: lineNumber || null,
  };
  if (asJson) {
    process.stdout.write(JSON.stringify(diag) + "\n");
  } else {
    process.stderr.write(`FAIL · ${diag.code}\n`);
    process.stderr.write(`  field:    ${diag.field}\n`);
    process.stderr.write(`  message:  ${diag.message}\n`);
    if (lineNumber) process.stderr.write(`  line:     ${lineNumber}\n`);
  }
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log(`
Usage:
  node scripts/research/validate-cli.js <path>          # validate one JSON file
  node scripts/research/validate-cli.js < payload.json  # validate stdin
  node scripts/research/validate-cli.js <path> --jsonl  # validate every line of a JSONL
  node scripts/research/validate-cli.js <path> --json   # emit machine-readable diagnostics

Exit codes:
  0 — all payloads valid
  3 — at least one payload invalid (SchemaViolationError or JSON parse error)
  2 — argv / IO error
`);
    process.exit(0);
  }

  const src = readSource(args);

  if (args.jsonl) {
    const lines = src.split(/\r?\n/);
    let ok = 0, fail = 0;
    let firstSummary = null;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      if (!line.trim()) continue;
      let parsed;
      try { parsed = JSON.parse(line); }
      catch (e) {
        emitFail(args.json, { code: "PARSE_ERROR", message: e.message, field: "$" }, i + 1);
        fail++;
        continue;
      }
      try {
        validatePayload(parsed, Buffer.from(line, "utf8"));
        ok++;
        if (!firstSummary) firstSummary = {
          format: parsed.format,
          cohort_code: parsed.cohort_code,
          consent_version: parsed.consent_version,
          upload_ts: parsed.upload_ts,
        };
      } catch (e) {
        emitFail(args.json, e, i + 1);
        fail++;
      }
    }
    if (fail === 0) {
      emitOk(args.json, { lines: ok, ...firstSummary });
      process.exit(0);
    } else {
      if (!args.json) process.stderr.write(`\n${ok}/${ok + fail} valid; ${fail} invalid\n`);
      process.exit(3);
    }
  }

  // Single payload mode.
  let parsed;
  try { parsed = JSON.parse(src); }
  catch (e) {
    emitFail(args.json, { code: "PARSE_ERROR", message: e.message, field: "$" });
    process.exit(3);
  }
  try {
    validatePayload(parsed, Buffer.from(src, "utf8"));
    emitOk(args.json, {
      lines: 1,
      format: parsed.format,
      cohort_code: parsed.cohort_code,
      consent_version: parsed.consent_version,
      upload_ts: parsed.upload_ts,
    });
    process.exit(0);
  } catch (e) {
    emitFail(args.json, e);
    process.exit(3);
  }
}

if (require.main === module) {
  try { main(); }
  catch (e) { console.error("validate-cli unhandled:", e && e.message ? e.message : e); process.exit(1); }
}
